### ISSUE TITLE
hybridd issue

### ISSUE THREAD

**Issue by dougbebber** [internetofcoins/hybridd#1]
When I start hybridd I get the following console output:

Starting hybridd...
 [i] using node executable /home/user/.nvm/versions/node/v6.10.3/bin/node
 [i] REST API running on: http://127.0.0.1:1111
 [i] user interface running on: http://127.0.0.1:8080
 [.] scanning modules in /home/user/ioc/hybridd/modules/
 [i] found module blockexplorer
 [i] found module deterministic
 [i] found module electrum
 [i] found module ethereum
 [i] found module lisk
 [.] loading module blockexplorer
 [.] loading module deterministic
 [.] loading module electrum
 [.] loading module ethereum
 [.] loading module lisk
 [i] module electrum: failed connection to [btc] host http://127.0.0.1:8338
 [i] module ethereum: connected to [eth] host https://api.myetherapi.com:443
 [i] module lisk: connected to [lsk] host https://liskworld.info:443

module electrum fails to connect.

When I attempt to access http://localhost:8080 hybridd terminates with the following output:
[.] routing request ["v","login"]
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '../views/login.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.serve (/home/user/ioc/hybridd/lib/view.js:1:338)
    at route (/home/user/ioc/hybridd/lib/router.js:1:1359)
    at Server.onUIRequest (/home/user/ioc/hybridd/lib/main.js:1:1304)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)

Stopped hybridd.

Any ideas on how I can correct this?

**Comment by dougbebber** [comment]
I determined that the reason why the electrum module failed was because I installed it prior to installing hybridd. I removed electrum and then ran the electrum (install/run) scripts and now the output I get is as follows:

Starting hybridd...
 [i] using node executable /home/user/.nvm/versions/node/v6.10.3/bin/node
 [i] REST API running on: http://127.0.0.1:1111
 [i] user interface running on: http://127.0.0.1:8080
 [.] scanning modules in /home/user/ioc/hybridd/modules/
 [i] found module blockexplorer
 [i] found module deterministic
 [i] found module electrum
 [i] found module ethereum
 [i] found module lisk
 [.] loading module blockexplorer
 [.] loading module deterministic
 [.] loading module electrum
 [.] loading module ethereum
 [.] loading module lisk
 [i] module electrum: connected to [btc] host http://127.0.0.1:8338
 [i] module ethereum: connected to [eth] host https://api.myetherapi.com:443
 [i] module lisk: connected to [lsk] host https://liskworld.info:443

However, when I try to access http://localhost:8080 hybridd still terminates:

 [.] routing request ["v","login"]
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '../views/login.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.serve (/home/user/ioc/hybridd/lib/view.js:1:338)
    at route (/home/user/ioc/hybridd/lib/router.js:1:1359)
    at Server.onUIRequest (/home/user/ioc/hybridd/lib/main.js:1:1304)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)

Stopped hybridd.

Any suggestions on how I might correct this?

**Comment by holosphere** [comment]
Thanks for trying our alpha release!

You get: Error: ENOENT: no such file or directory, open '../views/login.json'

Try generating the views json files before launching hybridd

cd views
./compileviews.sh 

We will include 'coldstart' script with new release, to make this more intuitive.

Oh yes, the connection to electrum daemon fails (in the first printout) probably because you need to create an electrum config file.

/home/yourusername/.electrum/config should contain:

{
    "rpcport": 8338
}

So it runs on the right port that hybridd expects. In the second output it works though, so if it ain't broke any more, don't fix it.

**Comment by dougbebber** [comment]
Thank you for your response.

the "compileviews.sh" script has some directory structure hard coded within it and so it didn't work for me. I changed it so that it performed the task on my machine and it worked. I was able to access the http://localhost:8080 page.

**Comment by dougbebber** [comment]
After manually compiling the views, I now have hybridd working properly.

Thank you.
