### ISSUE TITLE
Can't sign in with crowdfund login creds on iPhone using Chrome, Safari or FireFox

### ISSUE THREAD

**Issue by CodaSiren** [internetofcoins/hybridd#15]

**Comment by marcoalkema** [comment]
You are able to sign in through a desktop computer, but not with your iPhone?

**Comment by CodaSiren** [comment]
Issue solved and added to [FAQ](https://www.internetofcoins.org/faq#cannot-log-in).
Problem was using numbers 0 and 1 instead of capital letters O, L and I.
